// Keeps the README's "Tuning" table generated from src/lib/server/config.ts, so
// the documented thresholds cannot drift from the ones the pipeline runs with.
//
//   node --import tsx scripts/gen-config-docs.ts           # rewrite README.md
//   node --import tsx scripts/gen-config-docs.ts --check   # CI: exit 1 if stale
import { readFileSync, writeFileSync } from 'node:fs'
import { configSnapshot } from '../src/lib/server/config'
import { MAJOR_SEVERITY, SIGNAL_YES } from '../src/lib/signals'
import { WEIGHTS } from '../src/lib/server/trending-jev'

const START = '<!-- config:start (generated by scripts/gen-config-docs.ts — do not edit) -->'
const END = '<!-- config:end -->'

const NOTES: Record<string, string> = {
  JEV_MODEL: 'pinned; run `scripts/jev-regression.ts` with a candidate before moving it',
  JEV_THRESHOLD: 'P(relevant) at or above this is accepted',
  PAIR_BAND: 'nearest-story similarity band that gets a Jev "same story?" judgment',
  PAIR_YES: 'P(same) to join a story', PAIR_NO: 'P(same) at or below this rules the story out',
  STORY_MERGE: 'story-merge pass: window, candidate similarity, P(same) needed, caps',
  PURGE_BELOW: 'an accepted article Jev scores below this is removed again',
  EMBED_SIM_THRESHOLD: 'decides only the pairs Jev was unsure about or could not be asked about',
  MAJOR_SEVERITY: 'stories at or above it are checked against sensor readings (not shown to readers)',
  SIGNAL_YES: 'a yes/no signal at or above this shows as a badge',
  TRENDING_WEIGHTS: 'trending score = weighted Jev judgments + corroboration − talk penalty',
  JEV_POOL_CAP: 'most articles Jev judges for relevance per run',
  JEV_CONCURRENCY: 'parallel Jev requests',
  PAIR_CHUNK: 'articles judged + assigned per chunk, so later ones see stories earlier ones created',
  HEAD_POOL_CAP: 'most new articles the local head scores per run',
  HEAD_AUDIT_RATE: "share of the head's confident verdicts Jev judges anyway (agreement is recorded)",
  PURGE_CAP_PER_RUN: 'most removals per run — a bad question edit cannot empty the feed',
  SIGNALS_CAP: 'most articles annotated per run (worklist drains over following runs)',
  SIGNALS_LOOKBACK_HOURS: 'how far back the signals worklist looks',
  ASSIGN_CAP: 'most articles clustered per run, newest first',
  ASSIGN_LOOKBACK_HOURS: 'how far back the clustering worklist looks',
  STALE_WRITEOFF_HOURS: 'an unjudged article older than this is written off',
  AUTO_DISABLE_AFTER: 'consecutive failed fetches before a source is switched off',
  RUN_BUDGET_MS: 'the run bounds itself below the job timeout',
  CLASSIFY_BUDGET_MS: 'share of the run budget classification may use',
  IMAGE_FILL_CAP: 'most articles missing a photo that get an og:image fetch per run',
  IMAGE_FILL_CONCURRENCY: 'parallel page fetches for og:image',
  IMAGE_FILL_LOOKBACK_HOURS: 'how far back the image-fill worklist looks',
  UNREADABLE_RETRY_MINUTES: 'a page or photo that could not be read waits this long before the next try',
  LOW_YIELD: 'feeds reported as low-yield: ≥ minItems judged, ≤ maxPct accepted',
  SILENT: 'feeds reported as silent: fetched fine, ≤ maxItems new items in days (a stale file)',
}

function table(): string {
  const all: Record<string, unknown> = { ...configSnapshot(), MAJOR_SEVERITY, SIGNAL_YES, TRENDING_WEIGHTS: WEIGHTS }
  const rows = Object.entries(all).map(([k, v]) => `| \`${k}\` | \`${typeof v === 'object' ? JSON.stringify(v) : String(v)}\` | ${NOTES[k] ?? ''} |`)
  return [START, '', '| knob | value | what it does |', '|---|---|---|', ...rows, '', END].join('\n')
}

const readme = readFileSync('README.md', 'utf8')
const i = readme.indexOf(START)
const j = readme.indexOf(END)
if (i < 0 || j < 0) throw new Error('README.md is missing the config markers')
const next = readme.slice(0, i) + table() + readme.slice(j + END.length)
if (process.argv.includes('--check')) {
  if (next !== readme) {
    console.error('README.md "Tuning" table is stale — run: node --import tsx scripts/gen-config-docs.ts')
    process.exit(1)
  }
  console.log('README config table is current')
} else {
  writeFileSync('README.md', next)
  console.log('README.md updated')
}
