-- Feeds become DATA: the roster was operational state trapped in code
-- (feeds die, get WAF-blocked, need curating — all of that is now columns).
-- The pipeline loads 'where enabled' and writes health back every run; the
-- About page renders the roster; curation becomes UPDATEs instead of commits.

create table if not exists public.sources (
  id uuid primary key default gen_random_uuid(),
  url text unique not null,
  name text not null,
  region text not null,
  lang text not null,
  enabled boolean not null default true,
  last_ok_at timestamptz,
  last_via text,
  consecutive_failures int not null default 0,
  last_error_kind text,
  last_error text,
  updated_at timestamptz not null default now()
);

-- Public roster: the feed list has always been public in the repo, and the
-- About page renders it with health. Error details are fetch diagnostics only
-- (no secrets — the proxy key travels in a header, never in messages).
alter table public.sources enable row level security;
drop policy if exists "Public can read sources" on public.sources;
create policy "Public can read sources" on public.sources for select using (true);

insert into public.sources (name, url, region, lang) values
  ('Reuters', 'https://feeds.reuters.com/reuters/worldNews', 'US/Western', 'en'),
  ('AP News', 'https://rsshub.app/apnews/topics/ap-top-news', 'US/Western', 'en'),
  ('NPR World', 'https://feeds.npr.org/1004/rss.xml', 'US/Western', 'en'),
  ('CNN Middle East', 'https://rss.cnn.com/rss/edition_meast.rss', 'US/Western', 'en'),
  ('CNN World', 'https://rss.cnn.com/rss/edition_world.rss', 'US/Western', 'en'),
  ('Fox News Nat Sec', 'https://moxie.foxnews.com/google-publisher/national-security.xml', 'US/Western', 'en'),
  ('Fox News World', 'https://moxie.foxnews.com/google-publisher/world.xml', 'US/Western', 'en'),
  ('New York Times', 'https://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml', 'US/Western', 'en'),
  ('NYT World', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', 'US/Western', 'en'),
  ('Washington Post', 'https://feeds.washingtonpost.com/rss/world', 'US/Western', 'en'),
  ('NBC News', 'https://feeds.nbcnews.com/nbcnews/public/world', 'US/Western', 'en'),
  ('ABC News', 'https://abcnews.go.com/abcnews/internationalheadlines', 'US/Western', 'en'),
  ('CBS News', 'https://www.cbsnews.com/latest/rss/world', 'US/Western', 'en'),
  ('Newsweek', 'https://www.newsweek.com/rss', 'US/Western', 'en'),
  ('Axios World', 'https://api.axios.com/feed/topics/world', 'US/Western', 'en'),
  ('Politico', 'https://rss.politico.com/politics-news.xml', 'US/Western', 'en'),
  ('The Hill', 'https://thehill.com/feed/', 'US/Western', 'en'),
  ('The Atlantic', 'https://www.theatlantic.com/feed/all/', 'US/Western', 'en'),
  ('Voice of America', 'https://www.voanews.com/api/ztrqtqpym/rss.xml', 'US/Western', 'en'),
  ('Radio Free Europe', 'https://www.rferl.org/api/zmpiqormvy/rss.xml', 'US/Western', 'en'),
  ('UPI', 'https://rss.upi.com/news/world-news.rss', 'US/Western', 'en'),
  ('Foreign Policy', 'https://foreignpolicy.com/feed/', 'US/Western', 'en'),
  ('The Intercept', 'https://theintercept.com/feed/?rss', 'US/Western', 'en'),
  ('Stars and Stripes', 'https://www.stripes.com/arc/outboundfeeds/rss/?outputType=xml', 'US/Western', 'en'),
  ('Task & Purpose', 'https://taskandpurpose.com/feed/', 'US/Western', 'en'),
  ('Defense One', 'https://www.defenseone.com/rss/all/', 'US/Western', 'en'),
  ('Breaking Defense', 'https://breakingdefense.com/feed/', 'US/Western', 'en'),
  ('Defense News', 'https://www.defensenews.com/arc/outboundfeeds/rss/', 'US/Western', 'en'),
  ('BBC World', 'https://feeds.bbci.co.uk/news/world/middle_east/rss.xml', 'UK', 'en'),
  ('BBC World News', 'https://feeds.bbci.co.uk/news/world/rss.xml', 'UK', 'en'),
  ('The Guardian', 'https://www.theguardian.com/world/middleeast/rss', 'UK', 'en'),
  ('Guardian World', 'https://www.theguardian.com/world/rss', 'UK', 'en'),
  ('Sky News', 'https://feeds.skynews.com/feeds/rss/middle-east.xml', 'UK', 'en'),
  ('Sky News World', 'https://feeds.skynews.com/feeds/rss/world.xml', 'UK', 'en'),
  ('The Independent', 'https://www.independent.co.uk/news/world/rss', 'UK', 'en'),
  ('The Economist', 'https://www.economist.com/the-world-this-week/rss.xml', 'UK', 'en'),
  ('Middle East Eye', 'https://www.middleeasteye.net/rss', 'UK', 'en'),
  ('Financial Times', 'https://www.ft.com/world?format=rss', 'UK', 'en'),
  ('The Telegraph', 'https://www.telegraph.co.uk/rss.xml', 'UK', 'en'),
  ('The Spectator', 'https://www.spectator.co.uk/feed/', 'UK', 'en'),
  ('Channel 4 News', 'https://www.channel4.com/news/feed/atom', 'UK', 'en'),
  ('Deutsche Welle', 'https://rss.dw.com/rdf/rss-en-middle-east', 'European', 'en'),
  ('DW World', 'https://rss.dw.com/rdf/rss-en-all', 'European', 'en'),
  ('France 24', 'https://www.france24.com/en/middle-east/rss', 'European', 'en'),
  ('France 24 World', 'https://www.france24.com/en/rss', 'European', 'en'),
  ('Euronews', 'https://www.euronews.com/rss', 'European', 'en'),
  ('RFI English', 'https://www.rfi.fr/en/rss', 'European', 'en'),
  ('Swiss Info', 'https://www.swissinfo.ch/eng/rss/world', 'European', 'en'),
  ('Der Spiegel', 'https://www.spiegel.de/international/index.rss', 'European', 'en'),
  ('Politico Europe', 'https://www.politico.eu/feed/', 'European', 'en'),
  ('EUobserver', 'https://euobserver.com/feed', 'European', 'en'),
  ('El Pais English', 'https://feeds.elpais.com/mrss-s/pages/ep/site/english.elpais.com/portada', 'European', 'en'),
  ('Le Monde Diplo', 'https://mondediplo.com/feed/full', 'European', 'en'),
  ('Norwegian NRK', 'https://www.nrk.no/toppsaker.rss', 'European', 'no'),
  ('SVT Nyheter', 'https://www.svt.se/nyheter/rss.xml', 'European', 'sv'),
  ('Times of Israel', 'https://www.timesofisrael.com/feed/', 'Israeli', 'en'),
  ('Jerusalem Post', 'https://www.jpost.com/Rss/RssFeedsHeadlines.aspx', 'Israeli', 'en'),
  ('Haaretz', 'https://www.haaretz.com/cmlink/1.628765', 'Israeli', 'en'),
  ('Ynet News', 'https://www.ynet.co.il/Integration/StoryRss2.xml', 'Israeli', 'en'),
  ('i24 News', 'https://www.i24news.tv/en/rss', 'Israeli', 'en'),
  ('Arutz Sheva', 'https://www.israelnationalnews.com/Rss.aspx/News', 'Israeli', 'en'),
  ('Israel Hayom', 'https://www.israelhayom.com/feed/', 'Israeli', 'en'),
  ('Globes', 'https://en.globes.co.il/en/rss', 'Israeli', 'en'),
  ('Press TV', 'https://www.presstv.ir/homepagerss.aspx', 'Iranian State', 'en'),
  ('IRNA', 'https://en.irna.ir/rss', 'Iranian State', 'en'),
  ('Tasnim News', 'https://www.tasnimnews.com/en/rss', 'Iranian State', 'en'),
  ('Fars News', 'https://www.farsnews.ir/rss', 'Iranian State', 'en'),
  ('Mehr News', 'https://en.mehrnews.com/rss', 'Iranian State', 'en'),
  ('Tehran Times', 'https://www.tehrantimes.com/rss', 'Iranian State', 'en'),
  ('ISNA English', 'https://en.isna.ir/rss', 'Iranian State', 'en'),
  ('Iran Daily', 'https://www.iran-daily.com/rss', 'Iranian State', 'en'),
  ('Financial Tribune', 'https://financialtribune.com/rss', 'Iranian State', 'en'),
  ('Iran International', 'https://www.iranintl.com/en/feed', 'Iranian Independent', 'en'),
  ('Iran International (FA)', 'https://www.iranintl.com/feed', 'Iranian Independent', 'fa'),
  ('Radio Farda', 'https://www.radiofarda.com/api/ztrqtqpym/rss.xml', 'Iranian Independent', 'en'),
  ('Hamshahri', 'https://www.hamshahrionline.ir/rss', 'Iranian Local', 'fa'),
  ('Khabar Online', 'https://www.khabaronline.ir/rss', 'Iranian Local', 'fa'),
  ('ISNA Persian', 'https://isna.ir/rss', 'Iranian Local', 'fa'),
  ('Tabnak', 'https://www.tabnak.ir/fa/rss', 'Iranian Local', 'fa'),
  ('Mashregh News', 'https://www.mashreghnews.ir/rss', 'Iranian Local', 'fa'),
  ('Entekhab', 'https://www.entekhab.ir/rss', 'Iranian Local', 'fa'),
  ('Alef News', 'https://www.alef.ir/rss.xml', 'Iranian Local', 'fa'),
  ('Shargh Daily', 'https://sharghdaily.com/rss', 'Iranian Local', 'fa'),
  ('Aftab News', 'https://www.aftabnews.ir/rss', 'Iranian Local', 'fa'),
  ('Donya-e-Eqtesad', 'https://donya-e-eqtesad.com/rss', 'Iranian Local', 'fa'),
  ('Jahan News', 'https://www.jahannews.com/rss', 'Iranian Local', 'fa'),
  ('Raja News', 'https://www.rajanews.com/rss', 'Iranian Local', 'fa'),
  ('IRNA Isfahan', 'https://www.irna.ir/rss/taglist/84001', 'Iranian Local', 'fa'),
  ('IRNA Khorasan', 'https://www.irna.ir/rss/taglist/84008', 'Iranian Local', 'fa'),
  ('IRNA Khuzestan', 'https://www.irna.ir/rss/taglist/84011', 'Iranian Local', 'fa'),
  ('IRNA Kermanshah', 'https://www.irna.ir/rss/taglist/84013', 'Iranian Local', 'fa'),
  ('IRNA Fars', 'https://www.irna.ir/rss/taglist/84004', 'Iranian Local', 'fa'),
  ('Al Jazeera English', 'https://www.aljazeera.com/xml/rss/all.xml', 'Arab/Gulf', 'en'),
  ('Al Jazeera Arabic', 'https://www.aljazeera.net/aljazeerarss/a2/a2.xml', 'Arab/Gulf', 'ar'),
  ('Al Arabiya English', 'https://english.alarabiya.net/rss', 'Arab/Gulf', 'en'),
  ('Arab News', 'https://www.arabnews.com/rss.xml', 'Arab/Gulf', 'en'),
  ('Saudi Gazette', 'https://saudigazette.com.sa/rss', 'Arab/Gulf', 'en'),
  ('Gulf News', 'https://gulfnews.com/rss', 'Arab/Gulf', 'en'),
  ('The National (UAE)', 'https://www.thenationalnews.com/rss', 'Arab/Gulf', 'en'),
  ('Khaleej Times', 'https://www.khaleejtimes.com/rss.xml', 'Arab/Gulf', 'en'),
  ('KUNA', 'https://www.kuna.net.kw/rss', 'Arab/Gulf', 'en'),
  ('Kuwait Times', 'https://www.kuwaittimes.com/feed/', 'Arab/Gulf', 'en'),
  ('Qatar News Agency', 'https://www.qna.org.qa/en/rss', 'Arab/Gulf', 'en'),
  ('The Peninsula', 'https://www.thepeninsulaqatar.com/rss', 'Arab/Gulf', 'en'),
  ('Bahrain News Agency', 'https://www.bna.bh/en/rss', 'Arab/Gulf', 'en'),
  ('Oman News Agency', 'https://omannews.gov.om/rss', 'Arab/Gulf', 'en'),
  ('Jordan Times', 'https://www.jordantimes.com/rss/', 'Arab/Gulf', 'en'),
  ('Naharnet', 'https://www.naharnet.com/stories/en/rss', 'Arab/Gulf', 'en'),
  ('L''Orient Today', 'https://www.lorientlejour.com/rss', 'Arab/Gulf', 'en'),
  ('SANA (Syria)', 'https://sana.sy/en/?feed=rss2', 'Arab/Gulf', 'en'),
  ('Shafaq News', 'https://shafaq.com/en/rss', 'Arab/Gulf', 'en'),
  ('Iraqi News', 'https://www.iraqinews.com/feed/', 'Arab/Gulf', 'en'),
  ('Asharq Al-Awsat', 'https://english.aawsat.com/rss', 'Arab/Gulf', 'en'),
  ('Middle East Monitor', 'https://www.middleeastmonitor.com/feed/', 'Arab/Gulf', 'en'),
  ('Al-Monitor', 'https://www.al-monitor.com/rss', 'Arab/Gulf', 'en'),
  ('The New Arab', 'https://www.newarab.com/rss.xml', 'Arab/Gulf', 'en'),
  ('Mada Masr (Egypt)', 'https://www.madamasr.com/en/feed/', 'Arab/Gulf', 'en'),
  ('Al-Ahram', 'https://english.ahram.org.eg/rss.aspx/NewsContentID/2.aspx', 'Arab/Gulf', 'en'),
  ('Rudaw', 'https://www.rudaw.net/english/rss', 'Kurdish', 'en'),
  ('Kurdistan 24', 'https://www.kurdistan24.net/en/rss', 'Kurdish', 'en'),
  ('BasNews', 'https://www.basnews.com/en/rss', 'Kurdish', 'en'),
  ('NRT Digital', 'https://www.nrttv.com/en/rss', 'Kurdish', 'en'),
  ('Daily Sabah', 'https://www.dailysabah.com/rss', 'Turkish', 'en'),
  ('Hurriyet Daily', 'https://www.hurriyetdailynews.com/rss', 'Turkish', 'en'),
  ('Anadolu Agency', 'https://www.aa.com.tr/en/rss/default', 'Turkish', 'en'),
  ('TRT World', 'https://www.trtworld.com/rss', 'Turkish', 'en'),
  ('TASS', 'https://tass.com/rss/v2.xml', 'Russian', 'en'),
  ('RT', 'https://www.rt.com/rss/', 'Russian', 'en'),
  ('Sputnik', 'https://sputniknews.com/export/rss2/military_news/index.xml', 'Russian', 'en'),
  ('Sputnik World', 'https://sputniknews.com/export/rss2/world/index.xml', 'Russian', 'en'),
  ('RIA Novosti', 'https://ria.ru/export/rss2/world/index.xml', 'Russian', 'ru'),
  ('Meduza', 'https://meduza.io/en/rss/all', 'Russian', 'en'),
  ('The Moscow Times', 'https://www.themoscowtimes.com/rss', 'Russian', 'en'),
  ('Novaya Gazeta Europe', 'https://novayagazeta.eu/feed', 'Russian', 'en'),
  ('iStories', 'https://istories.media/feed/', 'Russian', 'ru'),
  ('Radio Svoboda', 'https://www.svoboda.org/api/ztrqtqpym/rss.xml', 'Russian', 'ru'),
  ('Xinhua', 'https://www.xinhuanet.com/english/rss/worldrss.xml', 'Chinese', 'en'),
  ('Global Times', 'https://www.globaltimes.cn/rss/outbrain.xml', 'Chinese', 'en'),
  ('China Daily', 'https://www.chinadaily.com.cn/rss/world_rss.xml', 'Chinese', 'en'),
  ('CGTN', 'https://www.cgtn.com/subscribe/rss/section/world-news.do', 'Chinese', 'en'),
  ('South China Morning Post', 'https://www.scmp.com/rss/91/feed', 'Chinese', 'en'),
  ('People''s Daily', 'http://en.people.cn/rss/politics.xml', 'Chinese', 'en'),
  ('Taiwan News', 'https://www.taiwannews.com.tw/feed/news', 'Chinese', 'en'),
  ('Taipei Times', 'https://www.taipeitimes.com/xml/index.rss', 'Chinese', 'en'),
  ('Focus Taiwan', 'https://focustaiwan.tw/rss', 'Chinese', 'en'),
  ('Dawn (Pakistan)', 'https://www.dawn.com/feeds/home', 'South Asian', 'en'),
  ('Geo News', 'https://www.geo.tv/rss/1', 'South Asian', 'en'),
  ('The News Intl', 'https://www.thenews.com.pk/rss/1/1', 'South Asian', 'en'),
  ('ARY News', 'https://arynews.tv/feed/', 'South Asian', 'en'),
  ('Samaa TV', 'https://www.samaa.tv/feed/', 'South Asian', 'en'),
  ('The Hindu', 'https://www.thehindu.com/news/international/?service=rss', 'South Asian', 'en'),
  ('Times of India', 'https://timesofindia.indiatimes.com/rssfeeds/296589292.cms', 'South Asian', 'en'),
  ('Hindustan Times', 'https://www.hindustantimes.com/feeds/rss/world/rssfeed.xml', 'South Asian', 'en'),
  ('NDTV', 'https://feeds.feedburner.com/ndtvnews-world-news', 'South Asian', 'en'),
  ('India Today', 'https://www.indiatoday.in/rss/1206578', 'South Asian', 'en'),
  ('The Wire', 'https://thewire.in/feed', 'South Asian', 'en'),
  ('The Print', 'https://theprint.in/feed/', 'South Asian', 'en'),
  ('Daily Star BD', 'https://www.thedailystar.net/feed/rss.xml', 'South Asian', 'en'),
  ('NHK World', 'https://www3.nhk.or.jp/nhkworld/en/news/feeds/rss.xml', 'East Asian', 'en'),
  ('Japan Times', 'https://www.japantimes.co.jp/feed/', 'East Asian', 'en'),
  ('Nikkei Asia', 'https://asia.nikkei.com/rss/feed/nar', 'East Asian', 'en'),
  ('Yonhap', 'https://en.yna.co.kr/RSS/news.xml', 'East Asian', 'en'),
  ('Korea Herald', 'https://www.koreaherald.com/rss/world.xml', 'East Asian', 'en'),
  ('Korea Times', 'https://www.koreatimes.co.kr/www/rss/rss.xml', 'East Asian', 'en'),
  ('Straits Times', 'https://www.straitstimes.com/news/asia/rss.xml', 'East Asian', 'en'),
  ('Channel News Asia', 'https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml', 'East Asian', 'en'),
  ('Africanews', 'https://www.africanews.com/feed/rss', 'African', 'en'),
  ('AllAfrica', 'https://allafrica.com/export/rss2/en/africa.xml', 'African', 'en'),
  ('Premium Times', 'https://www.premiumtimesng.com/feed', 'African', 'en'),
  ('The East African', 'https://www.theeastafrican.co.ke/tea/rss', 'African', 'en'),
  ('Daily Nation Kenya', 'https://nation.africa/rss.xml', 'African', 'en'),
  ('Mail & Guardian', 'https://mg.co.za/feed/', 'African', 'en'),
  ('Sudan Tribune', 'https://sudantribune.com/feed/', 'African', 'en'),
  ('Libya Herald', 'https://libyaherald.com/feed/', 'African', 'en'),
  ('Morocco World News', 'https://www.moroccoworldnews.com/feed/', 'African', 'en'),
  ('SABA Yemen Agency', 'https://saba.ye/en/showrss', 'Arab/Gulf', 'en'),
  ('Yemen Monitor', 'https://www.yemenmonitor.com/feed/', 'Arab/Gulf', 'en'),
  ('Libya Observer', 'https://www.libyaobserver.ly/feed', 'Arab/Gulf', 'en'),
  ('Egypt Independent', 'https://egyptindependent.com/feed/', 'Arab/Gulf', 'en'),
  ('Al-Arabiya Arabic', 'https://www.alarabiya.net/ar/rss.xml', 'Arab/Gulf', 'ar'),
  ('Xinhua Middle East', 'https://english.news.cn/middleeast/rss.xml', 'Arab/Gulf', 'en'),
  ('Global Voices MENA', 'https://globalvoices.org/regions/middle-east-north-africa/feed/', 'Arab/Gulf', 'en'),
  ('Bellingcat', 'https://www.bellingcat.com/feed/', 'Independent/OSINT', 'en'),
  ('The Cradle', 'https://thecradle.co/rss.xml', 'Independent/OSINT', 'en'),
  ('Mondoweiss', 'https://mondoweiss.net/feed/', 'Independent/OSINT', 'en'),
  ('Electronic Intifada', 'https://electronicintifada.net/feeds/news', 'Independent/OSINT', 'en'),
  ('+972 Magazine', 'https://www.972mag.com/feed/', 'Independent/OSINT', 'en'),
  ('War on the Rocks', 'https://warontherocks.com/feed/', 'Independent/OSINT', 'en'),
  ('Responsible Statecraft', 'https://responsiblestatecraft.org/feed/', 'Independent/OSINT', 'en'),
  ('The Grayzone', 'https://thegrayzone.com/feed/', 'Independent/OSINT', 'en'),
  ('CFR', 'https://www.cfr.org/rss', 'Independent/OSINT', 'en'),
  ('Lawfare', 'https://www.lawfaremedia.org/feed/', 'Independent/OSINT', 'en'),
  ('ISW', 'http://iswresearch.blogspot.com/feeds/posts/default', 'Independent/OSINT', 'en'),
  ('The Defense Post', 'https://thedefensepost.com/feed/', 'Independent/OSINT', 'en'),
  ('Brookings', 'https://www.brookings.edu/feed/', 'Independent/OSINT', 'en'),
  ('Carnegie Endowment', 'https://carnegieendowment.org/feed/', 'Independent/OSINT', 'en'),
  ('Global Voices', 'https://globalvoices.org/feed/', 'Independent/OSINT', 'en'),
  ('The Conversation', 'https://theconversation.com/global/articles.atom', 'Independent/OSINT', 'en'),
  ('Just Security', 'https://www.justsecurity.org/feed/', 'Independent/OSINT', 'en'),
  ('ACLED', 'https://acleddata.com/feed/', 'Independent/OSINT', 'en')
on conflict (url) do nothing;

-- Provenance FK on articles; rows keep their denormalized source_* columns
-- (the client needs them in one row) — this adds integrity + joinability.
alter table public.articles
  add column if not exists source_id uuid references public.sources(id) on delete set null;

update public.articles a
   set source_id = s.id
  from public.sources s
 where a.feed_url = s.url
   and a.source_id is null;
